import { chmodSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// The fixture is deliberately untracked. `omarchy plugin add` clones the whole
// repository into ~/.config/omarchy/plugins/<id> and `omarchy plugin update`
// needs that checkout to stay a git working tree, so there is no packaging step
// to exclude a file from: anything committed here installs on every user's
// machine. This generator ships; the executable it writes does not.
//
// String.raw keeps the body's backslashes literal, which is why the bash below
// reads as bash. It does not suppress `${...}` interpolation, and a backslash
// escape would survive String.raw into the output, so each literal dollar-brace
// is written as an interpolated "$".
//
// Keep the template ASCII. Bun 1.4.2's String.raw escapes non-ASCII characters
// to \uXXXX in the raw strings, which would corrupt the body silently.
//
// Run this as `bun run fixture`. Like the tests beside it, this file is ESM under
// a commonjs package.json, so node will not load it.
const FIXTURE = String.raw`#!/bin/bash
# Generated by test/make-fixture.js - do not edit. This file is untracked, so it
# never installs with the plugin; edit the generator instead.
#
# A test fixture for the QML harness: point the binaryPath setting at it.
# BoundedProcess clears the environment, so the one channel the harness has for
# steering this is a file under HOME, which the fixed environment does carry.
set -euo pipefail

fail_with=""
if [[ -r "${"$"}{HOME}/.fake-oxidone-exit" ]]; then
  fail_with="$(head -c 8 "${"$"}{HOME}/.fake-oxidone-exit" | tr -dc '0-9-')"
fi

entry() {
  printf '{"id":"%s","list":"L1","parent":null,"title":"%s","display_title":"%s","type":"task","has_notes":false,"due":"%s","status":"%s","completed_at":null,"position":"%s"}' \
    "$1" "$2" "$2" "$3" "$4" "$5"
}

case "${"$"}{1:-}" in
  --version)
    echo "oxidone 1.2.0"
    exit 0
    ;;
  json) ;;
  *)
    echo '{"error":{"kind":"usage","message":"fake: unexpected argument"}}' >&2
    exit 2
    ;;
esac

case "${"$"}{2:-}" in
  today)
    printf '{"today":"2026-09-12","entries":[%s,%s]}\n' \
      "$(entry a 'Send the signed contract back' 2026-09-09 needsAction 01)" \
      "$(entry b 'Reply to the accessibility audit' 2026-09-12 needsAction 02)"
    exit 0
    ;;
  lists)
    printf '{"lists":[{"id":"L1","title":"Reminders"},{"id":"L2","title":"Work"}]}\n'
    exit 0
    ;;
  tasks)
    printf '{"list":"%s","entries":[%s]}\n' "${"$"}{4:-L1}" \
      "$(entry a 'Send the signed contract back' 2026-09-09 needsAction 01)"
    exit 0
    ;;
  apply)
    command="$(head -c 4096)"
    if [[ -n $fail_with ]]; then
      printf '{"error":{"kind":"fake","message":"asked to fail with %s"}}\n' "$fail_with" >&2
      exit "$fail_with"
    fi
    op="$(printf '%s' "$command" | sed -n 's/.*"op":"\([a-z_]*\)".*/\1/p')"
    task="$(printf '%s' "$command" | sed -n 's/.*"task":"\([^"]*\)".*/\1/p')"
    echoed() { printf '{"entry":%s}\n' "$(entry "$1" 'Send the signed contract back' "$2" "$3" 01)"; }
    case "$op" in
      complete)   echoed "$task" 2026-09-09 completed ;;
      uncomplete) echoed "$task" 2026-09-09 needsAction ;;
      # Migrate always dates past today, which is what makes the row leave Today.
      migrate)    echoed "$task" 2026-09-13 needsAction ;;
      delete)     printf '{"deleted":{"list":"L1","id":"%s"}}\n' "$task" ;;
      *)
        printf '{"error":{"kind":"usage","message":"fake: unknown op"}}\n' >&2
        exit 2
        ;;
    esac
    exit 0
    ;;
  *)
    echo '{"error":{"kind":"usage","message":"fake: unknown subcommand"}}' >&2
    exit 2
    ;;
esac
`;

const out = fileURLToPath(new URL("fake-oxidone", import.meta.url));
writeFileSync(out, FIXTURE);
// writeFileSync only applies `mode` when it creates the file, so set it after.
chmodSync(out, 0o755);
console.log(`wrote ${out} (0755)`);
