import { chmodSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// The fixture is deliberately untracked. `omarchy plugin add` clones the whole
// repository into ~/.config/omarchy/plugins/<id> and `omarchy plugin update`
// needs that checkout to stay a git working tree, so there is no packaging step
// to exclude a file from: anything committed here installs on every user's
// machine. This generator ships; the executable it writes does not.
//
// String.raw keeps the body's backslashes literal, which is why the bash below
// reads as bash. It does not suppress `${...}` interpolation, and a backslash
// escape would survive String.raw into the output, so each literal dollar-brace
// is written as an interpolated "$".
//
// Keep the template ASCII. Bun 1.4.2's String.raw escapes non-ASCII characters
// to \uXXXX in the raw strings, which would corrupt the body silently.
//
// Run this as `bun run fixture`. Like the tests beside it, this file is ESM under
// a commonjs package.json, so node will not load it.
const FIXTURE = String.raw`#!/bin/bash
# Generated by test/make-fixture.js - do not edit. This file is untracked, so it
# never installs with the plugin; edit the generator instead.
#
# A test fixture for the QML harness: point the binaryPath setting at it.
# BoundedProcess clears the environment, so the one channel the harness has for
# steering this is a file under HOME, which the fixed environment does carry.
set -euo pipefail

# Digits only, so that whatever is in the file, what comes out of this is
# something exit will take. A hyphen in the class survived in the middle of a
# value ("1-2"), and bash's exit refuses that - after the error envelope has
# already gone out, leaving a half-answer that reads as the binary's own. The
# squeeze asks for exit 12 there instead, which is a wrong answer to a malformed
# question rather than no answer at all. No exit worth asking for is lost: the
# plugin's -1 is BoundedProcess saying the process never ran, which is not
# something a binary can return.
fail_with=""
if [[ -r "${"$"}{HOME}/.fake-oxidone-exit" ]]; then
  fail_with="$(head -c 8 "${"$"}{HOME}/.fake-oxidone-exit" | tr -dc '0-9')"
fi

# Which op the failure above applies to. Empty means every one of them. A
# Today capture is two Applies, and the half-capture branch is only reachable
# when the create lands and the set_due behind it does not, which needs a
# failure aimed at one op rather than at all of them.
fail_op=""
if [[ -r "${"$"}{HOME}/.fake-oxidone-fail-op" ]]; then
  fail_op="$(head -c 16 "${"$"}{HOME}/.fake-oxidone-fail-op" | tr -dc 'a-z_')"
fi

entry() {
  # due is a date or null on the wire, never an empty string, and the
  # difference matters: "" sorts before any date, so an undated entry emitted
  # that way would read as overdue in every consumer of this fixture.
  local due='null'
  [[ -n $3 ]] && due="\"$3\""
  printf '{"id":"%s","list":"L1","parent":null,"title":"%s","display_title":"%s","type":"task","has_notes":false,"due":%s,"status":"%s","completed_at":null,"position":"%s"}' \
    "$1" "$2" "$2" "$due" "$4" "$5"
}

case "${"$"}{1:-}" in
  --version)
    echo "oxidone 1.2.0"
    exit 0
    ;;
  json) ;;
  *)
    echo '{"error":{"kind":"usage","message":"fake: unexpected argument"}}' >&2
    exit 2
    ;;
esac

case "${"$"}{2:-}" in
  today)
    printf '{"today":"2026-09-12","entries":[%s,%s]}\n' \
      "$(entry a 'Send the signed contract back' 2026-09-09 needsAction 01)" \
      "$(entry b 'Reply to the accessibility audit' 2026-09-12 needsAction 02)"
    exit 0
    ;;
  lists)
    printf '{"lists":[{"id":"L1","title":"Reminders"},{"id":"L2","title":"Work"}],"default_list":"L1"}\n'
    exit 0
    ;;
  due)
    # The read the due editor resolves through. Pure in the real binary too, so
    # a failure here is only ever the one asked for.
    if [[ -n $fail_with && ( -z $fail_op || $fail_op == "due" ) ]]; then
      printf '{"error":{"kind":"invalid_due","message":"fake: asked to fail with %s"}}\n' "$fail_with" >&2
      exit "$fail_with"
    fi
    expr="${"$"}{*:3}"
    case "$expr" in
      # Anything that is not one of these is not a date, exactly as exit 2
      # invalid_due says of the real vocabulary's misses.
      today)             printf '{"input":"%s","due":"2026-09-12"}\n' "$expr" ;;
      tomorrow|+1d)      printf '{"input":"%s","due":"2026-09-13"}\n' "$expr" ;;
      +3d)               printf '{"input":"%s","due":"2026-09-15"}\n' "$expr" ;;
      [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])
                         printf '{"input":"%s","due":"%s"}\n' "$expr" "$expr" ;;
      *)
        printf '{"error":{"kind":"invalid_due","message":"fake: not a date"}}\n' >&2
        exit 2
        ;;
    esac
    exit 0
    ;;
  tasks)
    # A positional read of $4 answered as though a list had been named whenever
    # one was not: "json tasks" alone fell back to L1, and "json tasks --list"
    # with no id did the same. An id is an id only when --list says so; anything
    # else is the usage error the real CLI would give.
    if [[ ${"$"}{3:-} != "--list" || -z ${"$"}{4:-} ]]; then
      echo '{"error":{"kind":"usage","message":"fake: tasks needs --list <id>"}}' >&2
      exit 2
    fi
    printf '{"list":"%s","entries":[%s]}\n' "$4" \
      "$(entry a 'Send the signed contract back' 2026-09-09 needsAction 01)"
    exit 0
    ;;
  apply)
    command="$(head -c 4096)"
    op="$(printf '%s' "$command" | sed -n 's/.*"op":"\([a-z_]*\)".*/\1/p')"
    if [[ -n $fail_with && ( -z $fail_op || $fail_op == "$op" ) ]]; then
      printf '{"error":{"kind":"fake","message":"asked to fail with %s"}}\n' "$fail_with" >&2
      exit "$fail_with"
    fi
    task="$(printf '%s' "$command" | sed -n 's/.*"task":"\([^"]*\)".*/\1/p')"
    title="$(printf '%s' "$command" | sed -n 's/.*"title":"\([^"]*\)".*/\1/p')"
    due="$(printf '%s' "$command" | sed -n 's/.*"due":"\([^"]*\)".*/\1/p')"
    echoed() { printf '{"entry":%s}\n' "$(entry "$1" 'Send the signed contract back' "$2" "$3" 01)"; }
    titled() { printf '{"entry":%s}\n' "$(entry "$1" "$2" "$3" needsAction 01)"; }
    case "$op" in
      complete)   echoed "$task" 2026-09-09 completed ;;
      uncomplete) echoed "$task" 2026-09-09 needsAction ;;
      # Migrate always dates past today, which is what makes the row leave Today.
      migrate)    echoed "$task" 2026-09-13 needsAction ;;
      delete)     printf '{"deleted":{"list":"L1","id":"%s"}}\n' "$task" ;;
      # A created entry is undated, which is why a Today capture chains a
      # set_due behind it. The id is fixed so the chain is followable.
      create)     titled new "$title" "" ;;
      retitle)    titled "$task" "$title" 2026-09-09 ;;
      set_due)    titled "$task" 'Send the signed contract back' "$due" ;;
      clear_due)  titled "$task" 'Send the signed contract back' "" ;;
      *)
        printf '{"error":{"kind":"usage","message":"fake: unknown op"}}\n' >&2
        exit 2
        ;;
    esac
    exit 0
    ;;
  *)
    echo '{"error":{"kind":"usage","message":"fake: unknown subcommand"}}' >&2
    exit 2
    ;;
esac
`;

const out = fileURLToPath(new URL("fake-oxidone", import.meta.url));
writeFileSync(out, FIXTURE);
// writeFileSync only applies `mode` when it creates the file, so set it after.
chmodSync(out, 0o755);
console.log(`wrote ${out} (0755)`);
